name: images_picker
description: Flutter plugin for selecting images/videos from the Android and iOS image library, and taking pictures/videos with the camera,save image/video to album/gallery.
version: 1.2.12
homepage: https://github.com/chavesgu/images_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.chavesgu.images_picker
        pluginClass: ImagesPickerPlugin
      ios:
        pluginClass: ImagesPickerPlugin